### ISSUE TITLE
1 Issue / 1 Dude

### ISSUE THREAD

**Issue by Xkipper** [Excrulon/Tree-of-Savior-Experience-Viewer#12]
Hi
Today I downladed You're new update. But the new Exp row dont work.
http://i.imgur.com/eUeFzBR.jpg
Negative values. I set Rank 5 and JobLevel 8. Im corsair rank1 and class level 8.

Dude:
How I can edit the Experience Viewer's UI? I want a vertical version, or minimal. I have a bit  experience into C#.

**Comment by fxfighter-gaming** [comment]
To make it display vertically you could probably change the StackPanel Orientation to vertical in ShellView.xaml. I don't know if someone else would break by doing that but it'd get you most of the way there.

That's probably a good feature to add to the application, toggle between vertical/horizontal.

**Comment by Excrulon** [comment]
You can grab the latest release. This disables class experience as it's not working properly anyway.

https://github.com/Excrulon/Tree-of-Savior-Experience-Viewer/releases

I won't be implementing a vertical feature but you or someone else is more than welcome to and I'll accept the pull request. Start by forking/cloning this repo, opening the solution in visual studio, and play with the code. Probably want to search around for windows presentation/xaml tutorials.
