### ISSUE TITLE
Error polling for experience

### ISSUE THREAD

**Issue by zeemyself** [Excrulon/Tree-of-Savior-Experience-Viewer#13]
When I try open program it show as in the picture
![err](https://cloud.githubusercontent.com/assets/5433120/11551182/473edc08-99ba-11e5-8b3b-4f86ef652075.PNG)

**Comment by fxfighter-gaming** [comment]
Not sure how that happened but you can fix it by navigating to "%UserProfile%\AppData\Local\TOSExpViewer" and finding the most recently modified folder. Inside there is a user.config and you can find the value for rank/class level.

Change the rank to whatever your rank displays as on tosbase: http://www.tosbase.com/tools/skill-simulator/

**Comment by N3Designz** [comment]
same, i found bug Class EXP. if select class level over 10. it will show like that.
