### ISSUE TITLE
Error polling for experience

### ISSUE THREAD

**Issue by kaizeth** [Excrulon/Tree-of-Savior-Experience-Viewer#15]
![image](https://cloud.githubusercontent.com/assets/2314278/11611511/bbbd9d54-9c0c-11e5-942e-e240b889e43e.png)

Was constantly switching around the settings for rank and job level until hit this error. Now i cant get it to work again even after deleting the whole folder and re-extract from the zip file. Is there some other files that I need to delete to get a clean setting again?

**Comment by fxfighter-gaming** [comment]
Duplicate of #13 

Gotta wait for Excrulon to release another version.

**Comment by Excrulon** [comment]
I'll post one shortly here.

**Comment by kaizeth** [comment]
My apologies for not looking through the issues first.
Then I'll follow the manual option provided on the original thread.

Thank you.

**Comment by Excrulon** [comment]
Give this a try if you'd like. Thanks for the fix @fxfighter-gaming.

https://github.com/Excrulon/Tree-of-Savior-Experience-Viewer/releases/tag/1.0.2

**Comment by kaizeth** [comment]
Not sure what this fixes did but it did not cause error now when I select any class rank.
You might want to remove Class Level 15 from the selection as it will cause the error again.

Thank you.
